### ISSUE TITLE
 Windows does not support privileged mode

### ISSUE THREAD

**Issue by JosueCayola** [nodeshift/nodeshift#291]
Hi. I'm using Windows Subsystem for Linux. when I create the container. I get this error.
`docker-compose run --rm --service-ports --use-aliases backend - bash`

`ERROR: Cannot create container for service backend: Windows does not support privileged mode
`
I have activated the docker functions
`{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": true
}`

please help.

**Comment by lholmquist** [comment]
I'm not sure this is the correct repo for your issue.

what are you doing exactly?

**Comment by lance** [comment]
Closing this for now, as it is not clear what project this is for and how it relates to nodeshift. Feel free to open a new issue with more information if that's not the case.
