### ISSUE TITLE
Be able to update the buildConfig

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/nodeshift#338]
https://github.com/nodeshift/nodeshift/blob/master/lib/build-config.js#L121

**Comment by lholmquist** [comment]
I might have written this comment before i added the  flag that will recreate the build config, so lets remove this comment and then close this issue

**Comment by helio-frota** [comment]
sounds good, thanks for the review

**Comment by helio-frota** [comment]
reopen, I clicked on the close button
