### ISSUE TITLE
Test the changing of BUILD LOCATION

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/nodeshift#342]
https://github.com/nodeshift/nodeshift/blob/master/test/project-archiver-test.js#L6

**Comment by lholmquist** [comment]
I think this could probably be closed since i don't think this is a valued thing anymore.  There is no option to change this location in the api.

We should probably also just remove the TODO in the code

**Comment by helio-frota** [comment]
sounds good, thanks for the review.
