### ISSUE TITLE
ERROR self signed certificate in certificate chain

### ISSUE THREAD

**Issue by kozmoz** [nodeshift/nodeshift#368]
Apparently the --strictSSL option is removed in 3.0.0. After upgrading to the latest version from version 2.1.1 nodeshift breaks on my my corporate laptop.

The changelog of 3.0.0 mentions that `strictSSL` is removed because of the new API client. But there is no workaround given how to configure the new client to have similar behavior.

**Comment by kozmoz** [comment]
An older blog post talks about `osc.strictSSL` to configure the SSL option, but that one isn't woking either (anymore)

**Comment by lholmquist** [comment]
The kubernetes-client module that drives the openshift-rest-client(the module that nodeshift uses), is now responsible for getting your kube config and it does some magic to determine that you are using a self-signed cert, thats why that option was removed.   What platform are you on?

**Comment by kozmoz** [comment]
OpenShift Origin / OKD 3.11. Does this answer your question? Sorry I'm still an Open Shift noob.

**Comment by lholmquist** [comment]
@kozmoz are you still having issues?

**Comment by kozmoz** [comment]
Haven't looked back since. So I guess it's not an issue anymore
