### ISSUE TITLE
~/.kube/config file not found

### ISSUE THREAD

**Issue by kozmoz** [nodeshift/nodeshift#369]
Well not really a bug, but more of an improvement request.

When the user forgets to log in, the error shown is something like: 
~/.kube/config file not found

Would be more helpful to suggest the user to login using `oc` first.

**Comment by lholmquist** [comment]
I think if we wanted to make this error better,  i believe we are going to need to update it in the openshift-rest-client module, https://github.com/nodeshift/openshift-rest-client, since that is basically what is driving this module anyway

**Comment by lholmquist** [comment]
closing this,  like i said in the previous comment,  i think we need to do this in the openshift-rest-client code.
