### ISSUE TITLE
Docker Build or S2I build

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/nodeshift#37]
The F-M-P has the ability to create a docker build, which from what i understand uses your local docker to do the build before pushing up to openshift, and a S2I build, which we are currently doing

We should be able to support both these

**Comment by lance** [comment]
For the plain old docker build, does that mean I need to get bucharest-gold/centos7-nodejs ONBUILD images in order?

**Comment by lholmquist** [comment]
Oh snap. Maybe.  I haven't investigated to far into that rabbit hole yet

Sent from my iPhone

On Jun 22, 2017, at 6:48 PM, Lance Ball <notifications@github.com> wrote:

For the plain old docker build, does that mean I need to get
bucharest-gold/centos7-nodejs ONBUILD images in order?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bucharest-gold/nodeshift/issues/37#issuecomment-310523548>,
or mute the thread

**Comment by lholmquist** [comment]
A little more documentation on what the difference is,  https://maven.fabric8.io/#build-openshift

**Comment by lholmquist** [comment]
This issue sort of goes along with our "Nodeshift should also do plain Kube" discussions.

**Comment by lance** [comment]
Closing as we think this is a feature we are not pursuing.
