### ISSUE TITLE
Web App Flag

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/nodeshift#383]
Currently when someone wants to use nodeshift with the web app image, they need to use the the `--dockerImage` flag and specify the correct image.

I wonder if it would beneficial to have a flag named `--web-app` or something similar that could be used and just specify the image for the user.

So instead of this: `nodeshift deploy --dockerImage=nodeshift/ubi8-s2i-web-app` 

it would be this: `nodeshift deploy --web-app`

This flag only makes sense when calling deploy or build(build is actually part of deploy)

We would have to remember that it needs to work when using the API also, and not just the CLI

@helio-frota @alexalikiotis @danbev any thoughts on if this would be a nice add?

**Comment by lholmquist** [comment]
I also realize i'm creating this issue on Friday at almost 5,  so we can talk about it monday :)

**Comment by danbev** [comment]
@lholmquist Yeah I think that would make a nice addition.

**Comment by alexalikiotis** [comment]
@lholmquist Nice idea! Also, I think this issue will be good for me (if you think I can handle it) because I will see the nodeshift's codebase and I'll get a better understanding of how things work :)

**Comment by helio-frota** [comment]
@lholmquist @alexalikiotis yeah that sounds good :+1:

**Comment by lholmquist** [comment]
added in d1d0c1429b12e3a00ad2cf754ec14639ff79e581
