### ISSUE TITLE
Combine build-strategy tests

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/nodeshift#396]
It looks like the test here https://github.com/nodeshift/nodeshift/blob/master/test/definitions-tests/build-strategy-test.js and https://github.com/nodeshift/nodeshift/blob/master/test/build-strategy-test.js should be merged into the same file.

I would prefer these tests to live in the `test/definitions-test/build-strategy-test` file

**Comment by theashraf** [comment]
I'd like to help with this one

**Comment by lholmquist** [comment]
@theashraf go for it!!
