### ISSUE TITLE
Argument error, options.body when running `openshift` script

### ISSUE THREAD

**Issue by guegse** [nodeshift/nodeshift#436]
[nodeshift-reproducer.zip](https://github.com/nodeshift/nodeshift/files/4471017/nodeshift-reproducer.zip)

When running
```
npm install
npm run nodeshift
```
the following error occurs:
```
2020-04-13T18:08:05.169Z INFO uploading binary archive ...
2020-04-13T18:08:05.177Z ERROR Argument error, options.body.

```
The problem seems to be caused by binary-build.js, line 30 where a stream is passed as a body to the openShiftRestClient which is passed thru to request.js (2.88.2).

Platform: Windows 10
Node: v12.16.2
NPM: 6.14.4

This seems to be a regression bug. It also happens when running the tutorial at https://www.katacoda.com/openshift/courses/middleware/rhoar-getting-started-nodejs

**Comment by lholmquist** [comment]
@guegse we released a new version of nodeshift yesterday that should fix this issue.  the new version is 6.0.2

The underlying issue was with the underlying kubernetes-client@8.3.7.  we now pin the version to be 8.3.6 while we look into what happened.

**Comment by guegse** [comment]
Yes, this seems to work.
