### ISSUE TITLE
Flag to indicate a custom directory for resource files

### ISSUE THREAD

**Issue by oscarlnetoo** [nodeshift/nodeshift#491]
Is there any config to define a subdirectory below `.nodeshift/` that indicates where Openshift resources are stored?

I have two namespaces on my cluster (prod and dev) with different deployment configurations for each one.
I wanted to separate those deployment files in different folders, plus a way to tell nodeshift which of them to use while executing a deploy.

**Comment by lholmquist** [comment]
At the moment no,  but this could be an interesting feature.  Were you thinking that maybe in the `.nodeshift/` that you would have a prod and dev folder,  and then in those folders would be your deploymentConfig.  Then we would have a flag to tell nodeshift which one of those folders to use?  and if you had resources in the top level directory,  they would be shared between the sub directories?

**Comment by lholmquist** [comment]
> We could use that flag, but it would be less flexible than a new one like resourceDirectory . If the user had some weird names for their namespaces, he would need to use them instead of simple ones like dev, prod and test.

That sounds reasonable.

Lets walk through an example of how this would work.  A user has a cluster with a namespace, `cool-production-namespace`, (they have already logged in, and that namespace is set in their kube config)and they have a sub folder in the `.nodeshift` directory called `prod`.  Using the `resourceDirectory` flag they specify `prod`,  so nodeshift loads the resource files from that directory.

The naming of that sub directory and their cluster namespace are not related then.

**Comment by lholmquist** [comment]
I would need to look to see what the code does, because it has been a while,  but we might have to do something with the Imagestream and possibly build configs that are autocreated to name things prod/dev/etc.... so if you are running these "profiles" in the same namespace,  you don't use a dev image with a prod deployment

**Comment by lholmquist** [comment]
Perhaps instead of `resourceDirectory` we could use `resourceProfile` or `profile`?

**Comment by oscarlnetoo** [comment]
> Perhaps instead of `resourceDirectory` we could use `resourceProfile` or `profile`?

Nice suggestions. I would go with `resourceProfile`, but it is up to you 🙂

**Comment by lholmquist** [comment]
@oscarlnetoo I just released a 7.2.0 which includes the `--resourceProfile` flag

**Comment by oscarlnetoo** [comment]
@lholmquist Cool! As soon as I test it, I will let you know. Thanks a lot 🙂

**Comment by lholmquist** [comment]
I know you mentioned that you were using 2 different namespaces,  so this probably wouldn't matter,  but i wonder if we should be looking into tagging our imagestreams different based on the resourceProfile that is used?

This could be another enhancement in the future

**Comment by oscarlnetoo** [comment]
@lholmquist I am not sure. Do you mean in case of having different deployment configs for the same namespace?

**Comment by oscarlnetoo** [comment]
@lholmquist `resourceProfile` is working perfectly
