### ISSUE TITLE
update 'middleware' to `application services`

### ISSUE THREAD

**Issue by eichnera** [nodeshift/nodeshift#496]
BU is moving away from the term `middleware` and adopting `application services`... does it make sense to adopt this terminology here?

**Comment by lholmquist** [comment]
I did a quick find in the code base and i didn't find any instances of the words middleware.  But if there are some, then we could update

**Comment by lholmquist** [comment]
@eichnera are you talking about the description of the Nodeshift Organization, which reads "Red Hat Middleware Node.js"?

**Comment by lholmquist** [comment]
closing for now
