### ISSUE TITLE
Can we use nodeshift to build from source in git repo?

### ISSUE THREAD

**Issue by pyrobit** [nodeshift/nodeshift#510]
I was hopping to be able to run nodeshift pointing to my code in a private git enterprise repo and in the initial build it automatically set build trigger when git repo receives a push.
Is it currently available in nodeshift?
(sorry sending here, I did not find a place to post questions)

**Comment by lholmquist** [comment]
At the moment,  nodeshift only deploys the code that you have locally.   That could be an interesting feature to add,  "deploy from git repo".   I know there are templates available that can be used that let you point at a git repo.

A very basic template for a simple express.js application is located here:  https://github.com/nodeshift-starters/nodejs-rest-http/blob/master/.openshiftio/application.yaml

you would using the `oc` commands to apply the template.

**Comment by pyrobit** [comment]
Thanks for the reply @lholmquist .  One thing I did not get yet is how we create a git webhook endpoint in openshift I already have an existing build config and did not find a way to generate the github webhook, in in github it asks for payload url (from openshift) and in openshift I did not find how to generate this payload url to github. Can you point me to where I can learn this?
