### ISSUE TITLE
Cannot locate specified Dockerfile

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/nodeshift#525]
I'm getting this error when running Nodeshift for Minikube deployment:

```
2021-01-08T12:37:38.034Z ERROR (HTTP code 500) server error - Cannot locate specified Dockerfile: Dockerfile 
2021-01-08T12:37:38.034Z ERROR Status code 500
```

But I have a Dockerfile in the root dir:

```
09:38 $ ll | grep Dockerfile
-rw-rw-r--   1 hf hf    380 jan  8 09:35 Dockerfile
✔ ~/code/nodeshift/nodejs-messaging-work-queue/frontend [kafka-nodeshift L|✚ 3…2] 
```

Not sure if that is a bug or if I'm missing something

**Comment by lholmquist** [comment]
what is the repo you are using?   looks like it could be a bug

**Comment by helio-frota** [comment]
@lholmquist I'm using with this https://github.com/nodeshift-starters/nodejs-messaging-work-queue on the front-end part first
same behavior with `npx`

**Comment by lholmquist** [comment]
@helio-frota are you on a specific branch?  there isn't a Dockerfile on the main branches

**Comment by helio-frota** [comment]
@lholmquist I created the Dockerfile locally

**Comment by lholmquist** [comment]
@helio-frota I think i know whats going on.   The package.json in those examples have the files property with the list of files to use.  the Dockerfile is probably not in there,  so nodeshift skips it

**Comment by helio-frota** [comment]
@lholmquist that makes sense. I'll try again later then I'll post the result here, thanks

**Comment by helio-frota** [comment]
@lholmquist thanks for the information, like you wrote the issue is just missing to add Dockerfile in files section :+1:
