### ISSUE TITLE
Build and deploy hooks

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/nodeshift#59]
I just wanted to create this issue so i wouldn't forget.

It would be interesting if nodeshift had different "stages" that could be hooked into.

similar to how ember-deploy works:  http://ember-cli-deploy.com/

This sort of goes along with how the maven plugin allows you to supply different enrichers.

**Comment by lance** [comment]
"lifecycle" hooks

**Comment by lholmquist** [comment]
Closing this for now.  If we think we want to re-visit this in the future,  i'll re-open
